# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: NDI.NDITools
PackageVersion: 6.2.0.3
MinimumOSVersion: 10.0.0.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: NDI Tools
  Publisher: NDI
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.ndi.tv/Tools/NDI%206%20Tools.exe
  InstallerSha256: 9610EC7FD16CEAB328DF26CB1B62BBF18ACCFB2E8E50F0FE204ACF6601AC41D4
ManifestType: installer
ManifestVersion: 1.9.0
