# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: NDI.NDIRuntime
PackageVersion: 6.2.0.3
PackageLocale: en-US
Publisher: NDI
PublisherUrl: https://ndi.video/
PackageName: NDI Runtime
License: Proprietary
Copyright: Copyright © Vizrt NDI AB. All rights reserved.
ShortDescription: NDI Runtime Installer
Description: Bring NDI support to specific applications that require NDI libraries but their installers do not bundle them.
Moniker: ndiruntime
Tags:
- ndi
- runtime
- libndi
ManifestType: defaultLocale
ManifestVersion: 1.9.0
